config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#index'

  # - session routes, log in/out - #
  get '/login' => 'sessions#login'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#logout'

  # - multi-step sign-up routes - #
  post '/' => 'admins#account_create'
  get '/admin/account_setup' => 'admins#account_setup'
  post '/admin/account_setup' => 'admins#account_complete'

  # - store management routes - #
  get '/admin' => 'admins#dashboard'
  post '/admin' => 'admins#dashboard'
  get '/admin/add-staff' => 'admins#add_staff'
  post '/admin/add-staff' => 'admins#post_added_staff'
  get '/admin/settings' => 'admins#settings', :as => :admin_settings
  post '/admin/settings' => 'admins#settings'
  put '/admin/update_settings' => 'admins#update_settings'

  # - products - #
  get '/admin/products' => 'products#index'
  get '/admin/products/new' => 'products#new'
  post '/admin/products' => 'products#create'
  get '/admin/products/:id/edit' => 'products#edit', :as => :admin_products_edit
  get '/admin/products/:id' => 'products#show', :as => :admin_product
  put '/admin/products/:id' => 'products#update'
  delete '/admin/products/:id' => 'products#destroy', :as => :admin_product_delete

  # - orders - #
  get '/admin/orders' => 'orders#index', :as => :admin_orders
  get '/admin/orders/:id' => 'orders#show', :as => :admin_order

  # - customers - #
  # get '/admin/customers' => 'customers#index', :as => :admin_customers
  # post '/admin/customers' => 'customers#create', :as => :admin_customer

  # - stores - #
  post '/stores/:id' => 'stores#shopfront'
  get '/stores/:id' => 'stores#shopfront', :as => :store
  get '/products' => 'stores#products', :as => :store_product
  get '/guest' => 'stores#create_guest'
  post '/guest' => 'stores#create_guest'
  get '/orders' => 'stores#confirm_checkout'
  post '/orders' => 'stores#confirm_checkout'


  # put '/cart/:id' => 'stores#cart'

end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id             :integer          not null, primary key
#  user_id        :integer
#  store_id       :integer
#  guest_id       :integer
#  confirmed      :boolean
#  payment_status :string(255)
#  completed      :boolean
#  created_at     :datetime
#  updated_at     :datetime
#

class Order < ActiveRecord::Base
  belongs_to :store
  has_many :order_products
  has_many :products, through: :order_products
  belongs_to :user
  belongs_to :guest
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    authenticate_admin
    if @current_admin == nil || @current_admin.empty?
      redirect_to root_path
    else
      # View uses @stores to iterate through each store and store.products.
      @stores = @current_admin[0].stores
    end
  end

  def show
  end
end

app/views/orders/index.haml
.topbar
  %p Orders
.view-container
  %table.tablesorter-default#orders-index
    %thead
      %tr
        %th #
        %th Store
        %th Buyer
        %th Confirmed
        %th Payment Status
        %th Completed
        %th Products
        %th Total
    %tbody#tablesort
    - @stores.each do |store|
      - store.orders.each do |order|
        %tr
          / %td= link_to order.id, admin_order_path(order)
          %td= order.id
          %td= store.store_name
          - if order.user_id
            %td= "#{order.user.first_name} #{order.user.last_name}"
          - else
            %td= "#{order.guest.first_name} #{order.guest.last_name}"
          %td= order.confirmed
          %td= order.payment_status
          %td= order.completed
          %td= order.products.length
          / Add's up products prices for each order.
          - @price_array = []
          - order.products.each do |product|
            - @price_array << product.price.to_f
          - @total_price = @price_array.inject(0) { |sum, num| sum + num}
          %td= "$#{@total_price}"
          - @price_array = []