config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#index'

  # - session routes, log in/out - #
  get '/login' => 'sessions#login'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#logout'

  # - multi-step sign-up routes - #
  post '/' => 'admins#account_create'
  get '/admin/account_setup' => 'admins#account_setup'
  post '/admin/account_setup' => 'admins#account_complete'

  # - store management routes - #
  get '/admin' => 'admins#dashboard'
  post '/admin' => 'admins#dashboard'
  get '/admin/add-staff' => 'admins#add_staff'
  post '/admin/add-staff' => 'admins#post_added_staff'
  get '/admin/settings' => 'admins#settings', :as => :admin_settings
  post '/admin/settings' => 'admins#settings'
  put '/admin/update_settings' => 'admins#update_settings'

  # - products - #
  get '/admin/products' => 'products#index'
  get '/admin/products/new' => 'products#new'
  post '/admin/products' => 'products#create'
  get '/admin/products/:id/edit' => 'products#edit', :as => :admin_products_edit
  get '/admin/products/:id' => 'products#show', :as => :admin_product
  put '/admin/products/:id' => 'products#update'
  delete '/admin/products/:id' => 'products#destroy', :as => :admin_product_delete

  # - orders - #
  get '/admin/orders' => 'orders#index', :as => :admin_orders
  get '/admin/orders/:id' => 'orders#show', :as => :admin_order

  # - customers - #
  # get '/admin/customers' => 'customers#index', :as => :admin_customers
  # post '/admin/customers' => 'customers#create', :as => :admin_customer

  # - stores - #
  post '/stores/:id' => 'stores#shopfront'
  get '/stores/:id' => 'stores#shopfront', :as => :store
  get '/products' => 'stores#products', :as => :store_product
  get '/guest' => 'stores#create_guest'
  post '/guest' => 'stores#create_guest'
  get '/orders' => 'stores#confirm_checkout'
  post '/orders' => 'stores#confirm_checkout'


  # put '/cart/:id' => 'stores#cart'

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id           :integer          not null, primary key
#  title        :string(255)
#  image        :string(255)
#  description  :text
#  product_type :string(255)
#  price        :float
#  sku          :string(255)
#  weight       :float
#  quantity     :integer
#  url_handle   :string(255)
#  visibility   :boolean
#  store_id     :integer
#  created_at   :datetime
#  updated_at   :datetime
#

class Product < ActiveRecord::Base
  belongs_to :store
  has_and_belongs_to_many :collections
  has_many :order_products
  has_many :orders, through: :order_products
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController


  def index
    authenticate_admin
    if @current_admin == nil || @current_admin.empty?
      redirect_to root_path
    else
      # View uses @stores to iterate through each store and store.products.
      @stores = @current_admin[0].stores
    end
  end

  def new
    @products = Product.new
    @stores_array = @current_admin[0].stores.map { |store| [store.store_name, store.id] }
  end

  def create
    product = Product.create product_params
    redirect_to '/admin/products'
  end

  def show
    @product = Product.find params[:id]
  end

  def edit
    @product = Product.find params[:id]
    @stores_array = @current_admin[0].stores.map { |store| [store.store_name, store.id] }
  end

  def update
    product = Product.find params[:id]
    product.update product_params
    redirect_to '/admin/products'
  end

  def destroy
    product = Product.find params[:id]
    product.destroy
    redirect_to '/admin/products'
  end

  private
  def product_params
    params.require(:product).permit(
      :title,
      :image,
      :description,
      :product_type,
      :price,
      :sku,
      :weight,
      :quantity,
      :url_handle,
      :visibility,
      :store_id
    )
  end
end

app/views/products/edit.haml
.topbar
  %p
    %a{:href => '/admin/products'} Products /
    %a{:href => "/admin/products/#{@product.id}"}
      = "#{@product.title}"
    %span / edit

#edit-products-form
  = form_tag("/admin/products/#{@product.id}", method: :put, :class => 'form-horizontal') do
    = label_tag 'Title'
    = text_field_tag 'product[title]', "#{@product.title}", :class => 'form-control'
    = label_tag 'Image URL'
    = text_field_tag 'product[image]', "#{@product.image}", :class => 'form-control'
    = label_tag 'Description'
    = text_area_tag 'product[description]', "#{@product.description}", :class => 'form-control'
    = label_tag 'Type'
    = text_field_tag 'product[product_type]', "#{@product.product_type}", :class => 'form-control'
    = label_tag 'Price'
    = text_field_tag 'product[price]', "#{@product.price}", :class => 'form-control'
    = label_tag 'SKU'
    = text_field_tag 'product[sku]', "#{@product.sku}", :class => 'form-control'
    = label_tag 'Weight'
    = text_field_tag 'product[weight]', "#{@product.weight}", :class => 'form-control'
    = label_tag 'Quantity'
    = text_field_tag 'product[quantity]', "#{@product.quantity}", :class => 'form-control'
    = label_tag 'URL Handle'
    = text_field_tag 'product[url_handle]', "#{@product.url_handle}", :class => 'form-control'
    = label_tag 'Visibility'
    = select_tag('product[visibility]', options_for_select([['Show', true], ['Hide', false]]), :class => 'form-control')
    = label_tag 'Store'
    = select_tag("product[store_id]", options_for_select(@stores_array), :class => 'form-control')
    = submit_tag nil, class: 'btn btn-success btn-block', id: 'edit-submit'

app/views/products/index.haml
.topbar
  %p Products
  %a{:href => "/admin/products/new"}
    %div{:id => 'add-product-button', :class => 'btn btn-primary'} Add Product
.view-container
  %table.tablesorter-default#products-show
    %thead
      %tr
        %th Image
        %th Name
        %th Type
        %th Price
        %th Quantity
        %th Store
        %th Visibility
    %tbody#tablesort
    - @stores.each do |store|
      - store.products.each do |product|
        %tr
          %td= image_tag product.image, :class => 'images-list'
          %td= link_to product.title, admin_product_path(product)
          %td= product.product_type
          %td= "$#{product.price}"
          %td= product.quantity
          %td= store.store_name
          - if product.visibility == true
            %td Visible
          - else
            %td Hidden

app/views/products/new.haml
.topbar
  %p
    %a{:href => '/admin/products'} Products
    %span / new

#new-products-form
  = form_tag '/admin/products', :class => 'form-horizontal' do
    = label_tag 'Title'
    = text_field_tag 'product[title]', nil, :class => 'form-control'
    = label_tag 'Image URL'
    = url_field_tag 'product[image]', nil, :class => 'form-control'
    = label_tag 'Description'
    = text_field_tag 'product[description]', nil, :class => 'form-control'
    = label_tag 'Type'
    = text_field_tag 'product[product_type]', nil, :class => 'form-control'
    = label_tag 'Price'
    = text_field_tag 'product[price]', nil, :class => 'form-control'
    = label_tag 'SKU'
    = text_field_tag 'product[sku]', nil, :class => 'form-control'
    = label_tag 'Weight'
    = text_field_tag 'product[weight]', nil, :class => 'form-control'
    = label_tag 'Quantity'
    = text_field_tag 'product[quantity]', nil, :class => 'form-control'
    = label_tag 'URL Handle'
    = text_field_tag 'product[url_handle]', nil, :class => 'form-control'
    = label_tag 'Visibility'
    = select_tag('product[visibility]', options_for_select([['Show', true], ['Hide', false]]), :class => 'form-control')
    = label_tag 'Store'
    = select_tag("product[store_id]", options_for_select(@stores_array), :class => 'form-control')
    = submit_tag nil, class: 'btn btn-success btn-block', id: 'new-submit'

app/views/products/show.haml
.topbar
  %p
    %a{:href => '/admin/products'} Products
    = "/#{@product.title}"
.view-container
  #product-image-column
    = image_tag @product.image, :class => 'images-large'
    %p= @product.description

  #product-content
    %table.table
      %thead
        %tr
          %th{:colspan => 2}= @product.store.store_name
      %tbody.table-striped
        %tr
          %td
            %span Title
          %td= "#{@product.title}"
        %tr
          %td
            %span Type
          %td= "#{@product.product_type}"
        %tr
          %td
            %span Price
          %td= "$#{@product.price}"
        %tr
          %td
            %span Quantity
          %td= "#{@product.quantity}"
        %tr
          %td
            %span SKU
          %td= "#{@product.sku}"
        %tr
          %td
            %span Weight
          %td= "#{@product.weight}kg"
        %tr
          %td
            %span URL Handle
          %td= "#{@product.url_handle}"
        %tr
          %td
            %span Visibility
          - if @product.visibility == true
            %td Visible
          - else
            %td Hidden

    = link_to('Delete', admin_product_delete_path(@product), :data => { :method => :delete })
    = link_to('Edit', admin_products_edit_path)