config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#index'

  # - session routes, log in/out - #
  get '/login' => 'sessions#login'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#logout'

  # - multi-step sign-up routes - #
  post '/' => 'admins#account_create'
  get '/admin/account_setup' => 'admins#account_setup'
  post '/admin/account_setup' => 'admins#account_complete'

  # - store management routes - #
  get '/admin' => 'admins#dashboard'
  post '/admin' => 'admins#dashboard'
  get '/admin/add-staff' => 'admins#add_staff'
  post '/admin/add-staff' => 'admins#post_added_staff'
  get '/admin/settings' => 'admins#settings', :as => :admin_settings
  post '/admin/settings' => 'admins#settings'
  put '/admin/update_settings' => 'admins#update_settings'

  # - products - #
  get '/admin/products' => 'products#index'
  get '/admin/products/new' => 'products#new'
  post '/admin/products' => 'products#create'
  get '/admin/products/:id/edit' => 'products#edit', :as => :admin_products_edit
  get '/admin/products/:id' => 'products#show', :as => :admin_product
  put '/admin/products/:id' => 'products#update'
  delete '/admin/products/:id' => 'products#destroy', :as => :admin_product_delete

  # - orders - #
  get '/admin/orders' => 'orders#index', :as => :admin_orders
  get '/admin/orders/:id' => 'orders#show', :as => :admin_order

  # - customers - #
  # get '/admin/customers' => 'customers#index', :as => :admin_customers
  # post '/admin/customers' => 'customers#create', :as => :admin_customer

  # - stores - #
  post '/stores/:id' => 'stores#shopfront'
  get '/stores/:id' => 'stores#shopfront', :as => :store
  get '/products' => 'stores#products', :as => :store_product
  get '/guest' => 'stores#create_guest'
  post '/guest' => 'stores#create_guest'
  get '/orders' => 'stores#confirm_checkout'
  post '/orders' => 'stores#confirm_checkout'


  # put '/cart/:id' => 'stores#cart'

end

app/views/layouts/application.haml
<!DOCTYPE html>
%html{:lang => "en"}
  %head
    %meta{:charset => "UTF-8"}/
    %title Store Builder
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body{:class => @sidebar_reveal}
    #main-container{:class => @main_container_selector}
      - if @sidebar_reveal
        #sidebar
          = link_to(admin_path) do
            %li Dashboard
          = link_to(admin_orders_path) do
            %li Orders
          = link_to('#') do
            %li Customers
          = link_to(admin_products_path) do
            %li Products
          = link_to('#') do
            %li Collections
          = link_to(admin_settings_path) do
            %li Settings
          = link_to(logout_path, :data => {:method => :delete}) do
            %li Logout
      #yield{:class => @sidebar_reveal}
        = yield